const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
let page = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const mr = {
  'Farmer partnerships � Agricultural sourcing � Dhule, Maharashtra':'शेतकरी भागीदारी • कृषी खरेदी • धुळे, महाराष्ट्र',
  'FARMER PRODUCER COMPANY':'शेतकरी उत्पादक कंपनी','For buyers':'खरेदीदारांसाठी','For farmers':'शेतकऱ्यांसाठी','Emmer wheat':'खपली गहू','Other crops':'इतर पिके','FAQs':'प्रश्नोत्तरे','Our model':'आमचे कार्य','Talk to our team ?':'आमच्या टीमशी बोला',
  'From growers to businesses':'शेतकऱ्यांकडून व्यवसायांपर्यंत','Good grain starts with':'चांगल्या धान्याची सुरुवात','good partnerships.':'विश्वासाच्या भागीदारीतून होते.','Shetimay connects farmers with merchants and food businesses through cultivation support, direct procurement and dependable agricultural sourcing.':'शेतिमाय शेतकऱ्यांना व्यापारी आणि अन्न उद्योगांशी जोडते. आम्ही पीक लागवडीसाठी मार्गदर्शन, शेतकऱ्यांकडून थेट खरेदी आणि विश्वासार्ह कृषी उत्पादन पुरवठा करतो.','I�m a buyer':'मी खरेदीदार आहे','I�m a farmer':'मी शेतकरी आहे','Based in Dhule, Maharashtra � Focused on Emmer (Khapli) wheat':'धुळे, महाराष्ट्र येथे • खपली गहू हे मुख्य पीक','Emmer wheat � Khapli gahu':'खपली गहू','Our special focus crop':'आमचे मुख्य पीक',
  'Farmer-linked sourcing':'शेतकऱ्यांकडून थेट खरेदी','Work directly with growers in our network':'आमच्या शेतकरी गटातील उत्पादकांशी थेट व्यवहार','Flexible product preparation':'गरजेनुसार उत्पादनाची तयारी','Cleaning and processing by buyer requirement':'खरेदीदाराच्या गरजेनुसार स्वच्छता व प्रक्रिया','Rooted in Dhule':'धुळे येथे कार्यरत','Local knowledge, regional agricultural supply':'स्थानिक अनुभव आणि प्रादेशिक कृषी पुरवठा',
  'Our main focus crop':'आमचे मुख्य लक्ष असलेले पीक','Emmer wheat, sourced with care.':'खपली गहू, काळजीपूर्वक मिळवलेला.','Emmer wheat�known locally as Khapli gahu�is Shetimay�s main focus crop. We partner with farmers to support cultivation and procure the harvested grain for business buyers.':'खपली गहू हे शेतिमायचे मुख्य पीक आहे. आम्ही शेतकऱ्यांना लागवडीदरम्यान मार्गदर्शन करतो आणि काढणीनंतरचा गहू व्यापारी व उद्योगांसाठी थेट खरेदी करतो.','We can discuss supply as cleaned or processed grain, or as raw produce when that better suits your operation. Availability, quantity, preparation and delivery are confirmed for each enquiry.':'तुमच्या गरजेनुसार स्वच्छ केलेला किंवा प्रक्रिया केलेला गहू, तसेच कच्चा मालही उपलब्ध करून देण्याबाबत चर्चा करू शकतो. उपलब्धता, प्रमाण, प्रक्रिया आणि वितरणाची माहिती प्रत्येक चौकशीनुसार निश्चित केली जाते.','Raw grain':'कच्चा गहू','For buyers who prefer to handle processing':'प्रक्रिया स्वतः करू इच्छिणाऱ्या खरेदीदारांसाठी','Cleaning / processing':'स्वच्छता / प्रक्रिया','Options discussed to match your needs':'तुमच्या गरजेनुसार पर्याय','Useful for grain merchants, mills, processors and food businesses':'धान्य व्यापारी, गिरण्या, प्रक्रिया उद्योग आणि अन्न व्यवसायांसाठी','Share your required quantity, specification and destination':'आवश्यक प्रमाण, दर्जा आणि वितरणाचे ठिकाण कळवा','We�ll confirm current crop availability and commercial details directly':'सध्याची उपलब्धता आणि व्यावसायिक अटी आम्ही थेट कळवू','Enquire about Emmer wheat ?':'खपली गव्हासाठी चौकशी करा',
  'More produce, same farmer connection':'अधिक पिके, शेतकऱ्यांशी तेच थेट नाते','Wheat and maize sourcing.':'गहू आणि मक्याची खरेदी.','Alongside our main focus on Emmer wheat, we also procure other wheat varieties and maize from farmers for merchant and business buyers. Ask us about the current crop, quantity, quality and delivery options.':'खपली गव्हासोबतच आम्ही शेतकऱ्यांकडून गव्हाच्या इतर जाती आणि मका खरेदी करून व्यापारी व उद्योगांना पुरवतो. सध्याचे पीक, प्रमाण, गुणवत्ता आणि वितरणाच्या पर्यायांबद्दल विचारा.','WHEAT':'गहू','Other wheat varieties':'गव्हाच्या इतर जाती','We buy other types of wheat from farmers and supply them to merchants. Share the variety, expected quantity and your preferred product condition so we can check availability.':'आम्ही शेतकऱ्यांकडून गव्हाच्या इतर जाती खरेदी करून व्यापाऱ्यांना पुरवतो. उपलब्धता तपासण्यासाठी गव्हाची जात, अपेक्षित प्रमाण आणि उत्पादनाची अपेक्षित स्थिती कळवा.','Enquire about wheat ?':'गव्हासाठी चौकशी करा','MAIZE':'मका','Maize procurement':'मक्याची खरेदी','We also procure maize from farmers for merchants and companies. Contact us with your buying requirement and we�ll discuss available supply and terms.':'आम्ही व्यापारी आणि कंपन्यांसाठी शेतकऱ्यांकडून मका देखील खरेदी करतो. तुमची गरज कळवा; उपलब्ध पुरवठा आणि अटींबद्दल चर्चा करू.','Enquire about maize ?':'मक्यासाठी चौकशी करा',
  'Two sides of one supply chain':'एकाच पुरवठा साखळीतील दोन बाजू','How can Shetimay work with you?':'शेतिमाय तुमच्यासोबत कसे काम करू शकते?','Whether you grow the crop or need to source it, start with a conversation about what you need and what�s available.':'तुम्ही पीक घेणारे शेतकरी असाल किंवा उत्पादन खरेदी करू इच्छित असाल, तुमची गरज आणि उपलब्धता याबद्दल आमच्याशी बोला.','01 / FARMERS':'०१ / शेतकरी','Grow with a route to market':'विक्रीची खात्री असलेली लागवड','We provide seeds for selected crops, share cultivation guidance and purchase suitable harvests from farmers. Contact us to discuss crops, season, local availability and procurement terms.':'निवडक पिकांसाठी आम्ही बियाणे देतो, लागवडीदरम्यान मार्गदर्शन करतो आणि योग्य कापणीचा माल शेतकऱ्यांकडून खरेदी करतो. पीक, हंगाम, स्थानिक उपलब्धता आणि खरेदीच्या अटींबद्दल चर्चा करण्यासाठी संपर्क साधा.','Discuss farming with us ?':'शेतीविषयी चर्चा करा','02 / MERCHANTS & COMPANIES':'०२ / व्यापारी आणि कंपन्या','Source agricultural produce':'कृषी उत्पादन मिळवा','Tell us the crop, grade or quality requirements, quantity, preferred preparation and delivery location. We welcome enquiries for smaller lots and bulk quantities; supply depends on current availability. Our main focus is Emmer wheat, alongside other wheat varieties and maize.':'पीक, दर्जा किंवा गुणवत्तेची गरज, प्रमाण, अपेक्षित प्रक्रिया आणि वितरणाचे ठिकाण कळवा. कमी तसेच मोठ्या प्रमाणातील चौकशीचे स्वागत आहे; पुरवठा सध्याच्या उपलब्धतेवर अवलंबून आहे. खपली गव्हासोबत गव्हाच्या इतर जाती आणि मका ही आमची प्रमुख उत्पादने आहेत.','Discuss a buying requirement ?':'खरेदीची गरज कळवा',
  'Support through the crop cycle.':'पीक हंगामभर शेतकऱ्यांना साथ.','Our work begins before harvest. Shetimay provides seeds for selected crops, offers practical guidance during cultivation and connects farmers to procurement when produce is ready.':'आमचे काम कापणीपूर्वीच सुरू होते. शेतिमाय निवडक पिकांसाठी बियाणे देते, लागवडीदरम्यान उपयुक्त मार्गदर्शन करते आणि पीक तयार झाल्यावर शेतकऱ्यांना खरेदी प्रक्रियेशी जोडते.','Discuss seed availability and suitability before the season':'हंगामापूर्वी बियाण्यांची उपलब्धता आणि योग्यतेबद्दल विचारा','Get guidance and stay in touch as your crop grows':'पीक वाढत असताना मार्गदर्शन घ्या आणि संपर्कात रहा','Talk through harvest quality, quantity and procurement terms':'मालाचा दर्जा, प्रमाण आणि खरेदीच्या अटींबद्दल चर्चा करा','Build a direct relationship with a local farmer producer company':'स्थानिक शेतकरी उत्पादक कंपनीशी थेट संबंध जोडा','I�m a farmer � get in touch ?':'मी शेतकरी आहे • संपर्क साधा',
  'Built with farmers, season by season':'हंगामागणिक शेतकऱ्यांसोबत उभे','How we work':'आमची कार्यपद्धती','A practical farm-to-buyer connection.':'शेतापासून खरेदीदारापर्यंतचा थेट दुवा.','We coordinate across cultivation, procurement and preparation so farmers and buyers can discuss requirements with one local team.':'लागवड, खरेदी आणि मालाच्या तयारीचे समन्वय साधून शेतकरी व खरेदीदारांना आमच्या स्थानिक टीमशी थेट चर्चा करता येते.','STEP 01':'टप्पा ०१','Plan the crop':'पीक नियोजन','Discuss suitable seeds, crop plans and farmer requirements ahead of the season.':'हंगामापूर्वी योग्य बियाणे, पीक नियोजन आणि शेतकऱ्यांच्या गरजांबद्दल चर्चा करा.','STEP 02':'टप्पा ०२','Support cultivation':'लागवडीसाठी मदत','Stay connected with growers and share guidance through the growing cycle.':'पीक वाढीच्या काळात शेतकऱ्यांच्या संपर्कात राहून मार्गदर्शन देतो.','STEP 03':'टप्पा ०३','Procure the harvest':'मालाची खरेदी','Review produce availability, quality, quantity and terms with farmers.':'शेतकऱ्यांसोबत मालाची उपलब्धता, गुणवत्ता, प्रमाण आणि अटी ठरवतो.','STEP 04':'टप्पा ०४','Prepare for buyers':'खरेदीदारांसाठी तयारी','Coordinate raw or cleaned and processed supply according to the buyer enquiry.':'खरेदीदाराच्या गरजेनुसार कच्चा, स्वच्छ केलेला किंवा प्रक्रिया केलेला माल पुरवतो.',
  'Farmer and buyer questions':'शेतकरी आणि खरेदीदारांचे प्रश्न','Frequently asked questions.':'वारंवार विचारले जाणारे प्रश्न.','What to know before discussing a crop, seed or produce requirement with Shetimay.':'पीक, बियाणे किंवा कृषी उत्पादनाबद्दल शेतिमायशी चर्चा करण्यापूर्वी ही माहिती जाणून घ्या.','Does Shetimay buy produce directly from farmers?':'शेतिमाय शेतकऱ्यांकडून थेट माल खरेदी करते का?','Yes. We work with farmers on selected crops and procure suitable harvests for supply to merchants and businesses. Crop, quality, quantity, timing and terms are confirmed for each enquiry.':'होय. आम्ही निवडक पिकांसाठी शेतकऱ्यांसोबत काम करतो आणि व्यापारी व उद्योगांना पुरवण्यासाठी योग्य कापणीचा माल खरेदी करतो. पीक, गुणवत्ता, प्रमाण, वेळ आणि अटी प्रत्येक चौकशीनुसार निश्चित होतात.','Which crops can merchants and companies source?':'व्यापारी आणि कंपन्यांना कोणती पिके मिळू शकतात?','Emmer (Khapli) wheat is our main focus. We also procure other wheat varieties and maize. Availability changes with the crop and season, so contact us with your requirement.':'खपली गहू हे आमचे मुख्य पीक आहे. आम्ही गव्हाच्या इतर जाती आणि मका देखील खरेदी करतो. पीक आणि हंगामानुसार उपलब्धता बदलते; तुमची गरज आम्हाला कळवा.','Can I enquire about a small quantity or bulk supply?':'कमी किंवा मोठ्या प्रमाणात मालासाठी चौकशी करता येईल का?','Yes. We welcome enquiries for smaller lots and bulk quantities. Tell us the crop, approximate quantity, quality or grade, preparation and delivery location so we can discuss current availability.':'होय. कमी तसेच मोठ्या प्रमाणातील चौकशीचे स्वागत आहे. सध्याची उपलब्धता तपासण्यासाठी पीक, अंदाजे प्रमाण, गुणवत्ता किंवा दर्जा, प्रक्रिया आणि वितरणाचे ठिकाण कळवा.','Can you supply raw grain as well as cleaned or processed produce?':'कच्चा तसेच स्वच्छ किंवा प्रक्रिया केलेला माल मिळू शकतो का?','We can discuss raw produce or cleaning and processing options according to the crop and buyer requirement. Please include the product condition you need in your enquiry.':'पीक आणि खरेदीदाराच्या गरजेनुसार कच्चा माल किंवा स्वच्छता व प्रक्रियेच्या पर्यायांबद्दल चर्चा करता येईल. चौकशीत तुम्हाला हवा असलेला मालाचा प्रकार नमूद करा.','Do you provide seeds and farming guidance?':'तुम्ही बियाणे आणि शेतीविषयक मार्गदर्शन देता का?','We provide seeds for selected crops and discuss cultivation guidance with farmers. Contact us before the season to ask about the crop, seed availability and local suitability.':'निवडक पिकांसाठी आम्ही बियाणे देतो आणि शेतकऱ्यांना लागवडीबाबत मार्गदर्शन करतो. पीक, बियाण्यांची उपलब्धता आणि स्थानिक परिस्थितीतील योग्यतेबद्दल हंगामापूर्वी संपर्क साधा.','Looking for Emmer wheat or another crop?':'खपली गहू किंवा इतर पीक हवे आहे?','Send us your requirement and our team will follow up about availability.':'तुमची गरज कळवा; उपलब्धतेबद्दल आमची टीम संपर्क करेल.','Send a buyer enquiry ?':'खरेदीची चौकशी पाठवा',
  'Email us':'ईमेल करा','Email':'ईमेल','Let�s talk':'चला, बोलूया','Start with a conversation.':'चर्चेपासून सुरुवात करा.','Tell us whether you�re a farmer or a buyer, and include the crop, quantity and timing you have in mind. We�ll get back to you to discuss next steps.':'तुम्ही शेतकरी आहात की खरेदीदार, हे सांगून पीक, प्रमाण आणि अपेक्षित वेळ कळवा. पुढील तपशीलांसाठी आम्ही तुमच्याशी संपर्क साधू.','Call or WhatsApp':'फोन किंवा WhatsApp','Registered office':'नोंदणीकृत कार्यालय','What would you like to discuss?':'तुम्हाला कशाबद्दल चर्चा करायची आहे?','Choose the closest option to start a WhatsApp conversation. You can share more details directly with our team.':'WhatsApp संभाषण सुरू करण्यासाठी योग्य पर्याय निवडा. अधिक तपशील आमच्या टीमला थेट पाठवू शकता.','Farmer partnership':'शेतकरी भागीदारी','Seeds, crop guidance or selling produce':'बियाणे, पीक मार्गदर्शन किंवा मालाची विक्री','Buyer / merchant enquiry':'खरेदीदार / व्यापारी चौकशी','Emmer wheat, quantity and preparation':'खपली गहू, प्रमाण आणि प्रक्रिया','General enquiry':'सामान्य चौकशी','Email the Shetimay team':'शेतिमाय टीमला ईमेल करा','Connecting farmers, merchants and businesses through agricultural partnerships and produce sourcing in Maharashtra.':'महाराष्ट्रातील कृषी भागीदारी आणि उत्पादन खरेदीद्वारे शेतकरी, व्यापारी व व्यवसायांना जोडत आहोत.','Contact':'संपर्क','Instagram ?':'इन्स्टाग्राम ↗','Tawkheda, Dhule, Maharashtra, India':'तावखेडा, धुळे, महाराष्ट्र, भारत'
};

mr['Talk to our team'] = 'आमच्या टीमशी बोला';
mr["I'm a buyer"] = 'मी खरेदीदार आहे';
mr["I'm a farmer"] = 'मी शेतकरी आहे';
mr["I'm a farmer — get in touch"] = 'मी शेतकरी आहे • संपर्क साधा';
mr["We also procure maize from farmers for merchants and companies. Contact us with your buying requirement and we'll discuss available supply and terms."] = 'आम्ही व्यापारी आणि कंपन्यांसाठी शेतकऱ्यांकडून मका देखील खरेदी करतो. तुमची गरज कळवा; उपलब्ध पुरवठा आणि अटींबद्दल चर्चा करू.';

const bodyStart = page.indexOf('<body>') + 6;
const bodyEnd = page.lastIndexOf('</body>');
const scriptStart = page.lastIndexOf('  <script>', bodyEnd);
let body = page.slice(bodyStart, scriptStart);
const misses = new Set();
function translatedText(key) {
  const normalized = key.replaceAll("'", '\uFFFD').replaceAll('—', '\uFFFD').replaceAll('•', '\uFFFD');
  for (const candidate of [key, normalized, `${normalized} ?`]) {
    if (Object.hasOwn(mr, candidate)) return mr[candidate];
  }
  return undefined;
}
body = body.replace(/>([^<>]+)</g, (whole, text) => {
  const key = text.trim().replace(/\s+/g, ' ');
  const lookup = key.endsWith(' →') ? `${key.slice(0, -2)} ?` : key === 'Instagram ↗' ? 'Instagram ?' : key;
  const translated = translatedText(lookup);
  if (translated) return `>${text.match(/^\s*/)[0]}${translated}${text.match(/\s*$/)[0]}<`;
  if (/[A-Za-z]{3}/.test(key) && !['Shetimay'].includes(key)) misses.add(key);
  return whole;
});
page = page.slice(0, bodyStart) + body + page.slice(scriptStart);
page = page.replace(".step:not(:last-child):after{content:'?';", ".step:not(:last-child):after{content:'→';");
page = page.replace('<html lang="en">', '<html lang="mr">');
page = page.replace('<title>Shetimay | Emmer (Khapli) Wheat Sourcing & Farmer Partnerships</title>', '<title>शेतिमाय | खपली गहू, गहू आणि मका खरेदी</title>');
page = page.replace(/<meta name="description" content="[^"]*">/, '<meta name="description" content="शेतिमाय धुळे, महाराष्ट्रातील शेतकरी, व्यापारी आणि उद्योगांसाठी खपली गहू, गव्हाच्या इतर जाती व मका खरेदी करते. बियाणे, लागवड मार्गदर्शन आणि थेट खरेदीसाठी संपर्क साधा.">');
page = page.replace(/<meta property="og:title" content="[^"]*">/, '<meta property="og:title" content="शेतिमाय | खपली गहू, गहू आणि मका खरेदी">');
page = page.replace(/<meta property="og:description" content="[^"]*">/, '<meta property="og:description" content="शेतिमायसोबत शेतकरी, व्यापारी आणि उद्योगांसाठी थेट कृषी उत्पादन खरेदी.">');
page = page.replace('<meta property="og:url" content="https://shetimay.in/">', '<meta property="og:url" content="https://shetimay.in/mr/">');
page = page.replace('<link rel="canonical" href="https://shetimay.in/">', '<link rel="canonical" href="https://shetimay.in/mr/">');
  page = page.replace('<option value="mr">मराठी</option>', '<option value="mr" selected>मराठी</option>');
  page = page.replace('<option value="en" selected>English</option>', '<option value="en">English</option>');
  page = page.replace('Tawkheda, Shindkheda, Dhule', 'तावखेडा, शिंदखेडा, धुळे');
  page = page.replace('Maharashtra 425408, India', 'महाराष्ट्र ४२५४०८, भारत');
  page = page.replaceAll('>?</button>', '>☰</button>');
  page = page.replaceAll('<span aria-hidden="true">?</span>', '<span aria-hidden="true">→</span>');
  page = page.replaceAll('>?</div>', '>•</div>');
  page = page.replaceAll('>�</p>', '>©</p>');
  page = page.replace('<p>� <span id="year">', '<p>© <span id="year">');
  page = page.replace('alt="Shetimay logo"', 'alt="शेतिमायचा लोगो"');
  page = page.replace('alt="Khapli, also known as Emmer wheat, grown in Maharashtra"', 'alt="महाराष्ट्रात पिकवला जाणारा खपली गहू"');
  page = page.replace('alt="Emmer wheat, called Khapli gahu locally"', 'alt="खपली गहू"');
  page = page.replace('alt="A farmer�s crop and field from the Shetimay grower network"', 'alt="शेतिमायच्या शेतकरी गटातील शेत आणि पीक"');
page = page.replace("document.title=language==='mr'?'??????? | ???? ??? ??? ?????? ????????':language==='hi'?'?????? | ???? ????? ?? ????? ????????':'Shetimay | Emmer (Khapli) Wheat Sourcing & Farmer Partnerships';", 'if(language!==\'mr\') document.title=\'Shetimay | Emmer (Khapli) Wheat Sourcing & Farmer Partnerships\';');
page = page.replace(/\n\s*changeLanguage\('mr'\);\s*(?=\n\s*<\/script>)/, '');
fs.writeFileSync(path.join(root, 'mr', 'index.html'), page, 'utf8');
console.log(`Rebuilt Marathi page. Untranslated body snippets: ${[...misses].join(' | ')}`);
